### PR TITLE
adding willAnswer construct to allow custom answers

### PR DESCRIPTION
**Pull request by nadavwe**
@pijusn - WDYT?
it came up when talking with @opeled

### CODE REVIEW

**Comment by opeled** [comment]
@nadavwe you did not merge ??

**Comment by pijusn** [comment]
I think naming is confusing. Maybe it can be done with an implicit which converts lambda into a `CustomAction` so it would look like `will(addTwoNumbers)`, `will((_: String).toUpperCase))`, ... ? I just think `answer` is not the right word here. It's more like `willDelegate` or `willInvoke`.

**Comment by nargov** [comment]
I am wondering about the use case for this. 
The `willReturn(...)` and `will(returnValue(...))` constructs already provides a way to return an answer you want from a function invocation.
Wouldn't this encourage coupling between test code and production code?

**Comment by nadavwe** [comment]
the naming comes from mockito: https://static.javadoc.io/org.mockito/mockito-core/2.28.2/org/mockito/Mockito.html#10

**Comment by pijusn** [comment]
Released as `1.4.0`. Already available for download, should be visible in UIs in a matter of hours.

**Pull request merged**
